Feature
Shust0vD/hacker_news pull request #1
Opened 2022-08-10 13:36 UTC by Shust0vD

Выпонил задание (https://github.com/web-bee-ru/ru-test-assignments/blob/main/react/01-news-list.md).

codesandbox: https://codesandbox.io/s/goofy-gauss-u56jkn

2022-08-10 16:35 UTC, crutch12 commented
отдал @IRaccoonI

2022-08-16 08:32 UTC, IRaccoonI requested changes

2022-08-16 08:39 UTC, IRaccoonI commented
Все пункты задания сделаны
По коду: код хорший, есть косяки с отсутствием типизации

ещё по UX хочу сказать, у тебя на главной странице, при клике на "Update" кнопку, вообще ничего не проиходит для пользователя, и не понятно обновилось что-то, или нет

2022-08-16 08:59 UTC, Shust0vD commented
Ок, спасибо, начинаю исправлять.

2022-08-16 10:30 UTC, Shust0vD commented on src/components/Comments/Comment.tsx
> +      <div dangerouslySetInnerHTML={{ __html: `${comment.content}` }} />
Потому что в comment.content html разметка содержится с тегами и тд.
![image](https://user-images.githubusercontent.com/99994722/184858578-d1da5237-1f58-4a20-9ba4-ab4acc1ef3cc.png)

2022-08-16 16:26 UTC, Shust0vD commented
@IRaccoonI, исправил, можно смотреть.
Новый codesandbox: https://codesandbox.io/s/hacker-news-mscxim

2022-08-16 17:09 UTC, IRaccoonI requested changes

2022-08-16 17:09 UTC, IRaccoonI commented on src/pages/ItemPage/ItemPage.tsx
> +                {typeof itemNews?.url !== 'undefined' && itemNews?.url.indexOf('item?id=') == -1 ? (
выше вроде писал о этом же, `Boolean(undefined) === false`, так что нет смысла писать `typeof val === 'undefined'`

2022-08-16 17:09 UTC, IRaccoonI commented on src/pages/ItemPage/ItemPage.tsx
> +                {typeof itemNews?.url !== 'undefined' && itemNews?.url.indexOf('item?id=') == -1 ? (
и лучше стараться использовать `===`, ts даёт очень хорошую типизацию, чем строже ты по типам, тем легче будет поддерживать код, (=== - сравнивает с типом `2 !== '2'`, == - без типа, и вообще очень странная штука, вот тебе прикольный код `['1'] == 1`)

2022-08-16 17:09 UTC, IRaccoonI commented on src/components/Comments/Styles/CommentStyles.ts
> +export const CommentBlock = styled.div<{ marginLeft: `${number}px` }>`
если не проходил, то советую, https://github.com/type-challenges/type-challenges

2022-08-19 15:10 UTC, crutch12 approved these changes
Можно мержить 🚀

2022-08-19 15:11 UTC, merged